const data = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque gravida, est vel pulvinar gravida, quam mi mollis nibh, a consequat velit magna eu risus. Nulla a finibus tellus. Donec eu ante elementum, aliquet est nec, placerat velit. Cras ligula eros, sagittis eget malesuada vitae, semper eu nisl. Praesent viverra sit amet odio porttitor consectetur. Nullam ornare nisl purus, sit amet faucibus tortor commodo quis. Nam ut rutrum elit. Etiam non dapibus mauris, interdum consectetur urna. Curabitur dignissim magna odio, eget efficitur erat cursus vitae. Suspendisse rhoncus commodo urna sed sollicitudin. Aliquam vehicula, magna sed sollicitudin tempor, nisi dolor luctus erat, sit amet tincidunt nisi arcu eu lorem. Maecenas congue faucibus dui nec vulputate. Etiam urna ante, egestas ac pellentesque ac, porttitor suscipit elit. Nullam vehicula tristique vulputate. In accumsan enim ac sapien rutrum, quis scelerisque nisl tristique. Suspendisse id scelerisque velit.",
  "Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ullamcorper convallis egestas. Aliquam dictum erat ac nulla vestibulum, non facilisis leo vehicula. Ut viverra velit et libero accumsan, quis vestibulum dui convallis. In iaculis orci eget iaculis aliquet. Maecenas tristique ultrices dolor, in suscipit dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus tristique blandit risus sit amet consectetur. Cras metus orci, tincidunt sed dapibus nec, ultrices efficitur elit. Sed non lobortis tortor. Praesent suscipit quam sed ultricies cursus. Cras id tempus justo.",
  "Sed sollicitudin quam velit, non rhoncus tortor egestas vel. Proin tempus facilisis mi vitae varius. Cras ullamcorper aliquam justo in posuere. Praesent maximus, lectus quis fermentum eleifend, neque nisi blandit arcu, vitae sollicitudin eros nibh eget massa. Pellentesque facilisis non lorem vel lobortis. Phasellus vulputate tortor vitae libero dictum, nec finibus magna molestie. Donec vulputate turpis magna, eget malesuada urna lacinia id. Cras urna diam, condimentum non diam viverra, fermentum ullamcorper quam. Aenean vulputate neque et commodo elementum. Cras tempor sit amet ipsum sit amet efficitur. In vulputate finibus tempus. Aenean arcu urna, aliquam ut pulvinar id, posuere quis sem. Ut elementum tincidunt dui nec porttitor. Nam urna dolor, ultrices non condimentum sit amet, rhoncus sit amet risus. Quisque tempor at magna vel vestibulum.",
  "Quisque vulputate dui nunc, eu tempus odio tincidunt sit amet. Praesent vestibulum enim a diam imperdiet dignissim. Nulla facilisi. Duis finibus, augue sed suscipit faucibus, nisi ligula aliquam enim, non imperdiet erat odio sit amet sapien. Duis vitae erat quis est lobortis consequat quis mollis metus. Donec blandit magna nunc, sed volutpat libero scelerisque sit amet. Fusce quis arcu convallis, cursus turpis at, consequat risus. Maecenas sed sagittis enim. Suspendisse hendrerit risus vitae dictum placerat. Mauris sit amet felis eu odio pellentesque convallis eu in felis. Suspendisse iaculis ligula at fermentum euismod. Curabitur eget ante arcu.",
  "Vestibulum consectetur condimentum sollicitudin. Duis bibendum sapien eu erat interdum, vitae gravida augue facilisis. Curabitur quis euismod nunc. Nunc vulputate lectus sit amet nisi molestie pellentesque. Vivamus tellus sem, varius et justo id, aliquet blandit erat. Donec in urna bibendum, iaculis est ac, laoreet justo. Proin egestas volutpat scelerisque. Quisque maximus dapibus luctus. Maecenas sit amet justo urna. Fusce quis commodo nisi. Nam sodales fringilla nibh id consectetur. Vestibulum accumsan et sapien at rhoncus.",
  "Praesent hendrerit ante in dolor rhoncus, in tristique libero ultricies. Proin tempus placerat nisl vel luctus. Nullam interdum sollicitudin ligula, a sodales eros. Aliquam vulputate luctus euismod. Curabitur sagittis eros justo, vitae dignissim erat finibus eu. Suspendisse mollis odio turpis, at efficitur nunc varius sit amet. Duis quis laoreet dolor.",

  "Nulla sit amet justo sapien. Nullam vitae purus a metus hendrerit vehicula. Sed ut efficitur sem, et vehicula arcu. Sed lacinia quam magna, vel tristique ipsum tristique sed. Aenean id elit eu erat aliquam tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec euismod nisi augue, ac malesuada enim congue nec. Mauris sit amet venenatis dui, vitae pulvinar lorem. Nam lectus nibh, finibus in urna ut, lobortis dignissim odio. Nam ac velit ac dolor euismod varius sed at orci. Proin consectetur quam lacus, vitae fermentum ex tristique eu. Nunc condimentum vestibulum commodo. Sed a ullamcorper tellus, ut venenatis quam. Fusce a ultrices purus.",
  "Sed quis magna dignissim, pretium mauris ac, tincidunt nulla. Maecenas vel commodo lacus, a ullamcorper purus. Maecenas ut mi odio. Proin semper velit et suscipit ornare. Fusce ac turpis sapien. Nam sit amet ligula id sapien tincidunt pellentesque vel vestibulum turpis. Duis vehicula felis in lobortis varius. Aliquam bibendum tortor ac iaculis fringilla. Pellentesque id nunc vitae urna bibendum fringilla sollicitudin sodales arcu. Curabitur volutpat massa eget nisl sollicitudin sollicitudin. Donec consequat velit non ex pellentesque, ut viverra diam gravida. Sed mattis euismod orci at consequat. Duis suscipit turpis turpis, eu pharetra arcu faucibus id.",
  "Fusce consequat id arcu quis pretium. In pharetra nulla erat, eu ultrices velit sollicitudin laoreet. Aliquam et laoreet neque. Nulla faucibus fermentum magna vel tincidunt. Donec egestas nibh elementum tellus porttitor laoreet. Nullam lacus est, porta eleifend egestas sed, porttitor in tellus. Nulla interdum odio eget augue volutpat, id dignissim urna volutpat. Morbi lobortis arcu in consequat tempus. Aliquam non dolor et lectus semper molestie. Maecenas feugiat sapien ut ante maximus tristique. Suspendisse venenatis lacus eros, non commodo augue interdum pharetra. Nunc et augue eleifend, varius est et, varius elit. Cras aliquam tortor nec augue sodales, et rutrum enim sagittis.",
  "Cras mollis nibh neque, id auctor est rutrum sit amet. Donec rutrum scelerisque est id tempus. Phasellus tincidunt ut libero hendrerit porttitor. Mauris convallis leo id sagittis fringilla. Phasellus facilisis nisi orci, eget ullamcorper dui tincidunt in. Suspendisse dictum, turpis molestie hendrerit vestibulum, risus risus ornare mauris, id elementum mi neque id nisi. Sed id euismod nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi posuere nisl id odio imperdiet, ac ullamcorper risus consequat. Aenean porta posuere blandit.",
  "Integer imperdiet et sapien nec dictum. Vestibulum varius dignissim urna, eget cursus dui sodales non. Phasellus condimentum mi vel urna convallis tincidunt. Proin nec felis in eros luctus dignissim. Pellentesque nunc ligula, imperdiet vitae orci sit amet, eleifend sagittis mi. Praesent non felis nec lacus maximus tincidunt nec eget nunc. Pellentesque sit amet eros non quam pharetra accumsan. Maecenas porta tortor nec faucibus euismod. Integer id sapien in felis mollis convallis efficitur a libero. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent sed ante sem. Pellentesque eget purus tristique, bibendum dolor quis, pharetra orci. Mauris odio dui, congue in finibus in, consectetur id eros. Curabitur neque ex, posuere vitae vestibulum id, finibus a tellus. Nam nec finibus neque, a imperdiet urna. Integer in arcu ut sapien molestie consectetur quis a urna.",

  "Morbi non leo pulvinar, porttitor neque sit amet, posuere quam. Integer aliquam, arcu ac tincidunt pellentesque, felis ipsum ornare purus, id interdum est odio nec neque. Pellentesque in cursus sapien, ut suscipit sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut nec leo posuere, maximus ante et, blandit nisi. Curabitur sagittis tortor eu erat dapibus gravida. Suspendisse eu dictum massa. Curabitur suscipit quam sed pulvinar vulputate.",
  "Fusce arcu urna, auctor nec ligula et, tempus porttitor augue. Morbi placerat nisi egestas nisi semper volutpat. Etiam sit amet purus ac diam malesuada tempus. Nulla orci lorem, tincidunt a scelerisque sed, imperdiet a libero. Morbi turpis neque, blandit quis dapibus ultrices, placerat ut nibh. Nulla dolor felis, suscipit vel lobortis non, scelerisque a mauris. Duis pretium nisl velit, a blandit diam tristique id. Pellentesque vel purus ut mauris sodales suscipit nec vitae metus. Duis diam massa, euismod id lectus vitae, ultrices tristique sem.",
  "Nam eget scelerisque nisi. Nunc massa neque, lacinia ac ultricies in, eleifend at felis. Aenean sed augue eu massa maximus sodales. Donec arcu ante, facilisis ac dui eget, luctus euismod tellus. Fusce fringilla neque non magna fringilla eleifend. Duis eu faucibus dui, non condimentum lacus. Ut bibendum et turpis placerat dapibus. Aliquam erat volutpat. Nunc id leo tempor, porttitor sem at, mattis sapien. Sed sed feugiat sem. In a orci pellentesque nisi blandit commodo. Maecenas posuere at metus a egestas. Mauris quis magna diam. Fusce hendrerit scelerisque sapien at venenatis.",

  "Etiam urna quam, venenatis sit amet felis vitae, mollis dictum dolor. Ut pharetra magna at tempor tincidunt. Vestibulum nec purus pharetra, ornare mi ut, interdum lacus. Nunc non cursus nisl. Nam vestibulum congue odio, in commodo lorem efficitur sit amet. Donec dignissim orci tellus, et varius neque imperdiet sit amet. Phasellus euismod lectus magna, mattis dictum lorem fermentum a. Ut efficitur nisl vitae ante tincidunt fermentum. Mauris cursus lacinia efficitur. Mauris vel dolor vitae ligula dapibus viverra at ut ex.",

  "Phasellus eu justo turpis. Integer euismod leo lacus, in molestie nulla volutpat nec. Aenean in quam non tortor eleifend accumsan quis et urna. Suspendisse potenti. In dignissim, justo in fermentum porta, erat orci sollicitudin neque, et iaculis nisl massa eget est. Phasellus facilisis dui non massa rhoncus, vel scelerisque purus volutpat. Nam eleifend rhoncus elit. Etiam at hendrerit eros. Nulla fringilla accumsan eros, nec semper libero euismod ac.",

  "Sed quis justo est. Donec lacinia massa sed lacus suscipit fermentum. Curabitur sit amet lacus fermentum, scelerisque est quis, convallis orci. Phasellus mollis egestas augue, quis ullamcorper massa egestas sit amet. Suspendisse eu tortor et eros dignissim finibus. Aenean convallis efficitur metus, at fringilla mi molestie a. Aenean luctus libero eget consequat consequat. Curabitur rutrum eu felis sit amet pulvinar.",
];

// console.log(data);

export default data;
